---
kind: Template
apiVersion: v1
metadata:
  name: "${NAME}-deployment-template"
  creationTimestamp: 
objects:

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "${NAME}"
    labels:
      name: ${NAME}
      app: ${APP_GROUP}
      app-group: ${APP_GROUP}
    annotations:
      description: Defines how to deploy ${NAME}
  spec:
    strategy:
      type: Rolling
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - "${NAME}"
        from:
          kind: ImageStreamTag
          namespace: "${IMAGE_NAMESPACE}"
          name: "${SOURCE_IMAGE_NAME}:${TAG_NAME}"
    replicas: 1
    selector:
      name: "${NAME}"
    template:
      metadata:
        name: "${NAME}"
        labels:
          name: ${NAME}
          app: ${APP_GROUP}
          app-group: ${APP_GROUP}
      spec:
        containers:
        - name: "${NAME}"
          image: ''
          ports:
          - containerPort: 8080
            protocol: TCP
          env:
          - name: NODE_ENV
            value: production
          - name: POSTGRES_SERVER_HOST
            value: whis-db
          - name: POSTGRES_SERVER_PORT
            value: '5432'
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: whis
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: whis
                key: password
          - name: POSTGRES_DB
            value: whis
          - name: VECTRONICS_URL
            value: "${VECTRONICS_URL}"
          - name: whis_CHES_USERNAME
            valueFrom:
              secretKeyRef:
                name: ches
                key: whis_CHES_USERNAME
          - name: whis_CHES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ches
                key: whis_CHES_PASSWORD
          - name: whis_CHES_API_URL
            value: "${whis_CHES_API_URL}"
          - name: whis_CHES_AUTH_URL
            value: "${whis_CHES_AUTH_URL}"
          - name: whis_CHES_TO_EMAIL
            value: "${whis_CHES_TO_EMAIL}"
          - name: whis_CHES_FROM_EMAIL
            value: "${whis_CHES_FROM_EMAIL}"
          resources:
            limits:
              cpu: "${CPU_LIMIT}"
              memory: "${MEMORY_LIMIT}"
            requests:
              cpu: "${CPU_REQUEST}"
              memory: "${MEMORY_REQUEST}"

- kind: Service
  apiVersion: v1
  metadata:
    name: "${NAME}"
    labels:
      name: ${NAME}
      app: ${APP_GROUP}
      app-group: ${APP_GROUP}
    annotations:
      description: Exposes and load balances the application pods.
  spec:
    ports:
    - name: 3000-tcp
      protocol: TCP
      port: 3000
      targetPort: 3000
    selector:
      name: "${NAME}"
    type: ClusterIP
    sessionAffinity: None

parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all of the resources defined in this template.
  required: true
  value: whis-api
- name: APP_GROUP
  displayName: App Group
  description: Used to group components together.
  required: true
  value: whis
- name: SOURCE_IMAGE_NAME
  displayName: Source Image Name
  description: The name of the image to use for this resource.
  required: true
  value: whis-api 
- name: IMAGE_NAMESPACE
  displayName: Image Namespace
  description: The namespace of the OpenShift project containing the imagestream for the application.
  required: true
  value: 0dff19-tools
- name: TAG_NAME
  displayName: Environment TAG name
  description: The TAG name for this environment, e.g., dev, test, prod
  required: true
  value: dev
- name: APPLICATION_DOMAIN
  description: The exposed hostname that will route to the service, e.g., myappname.pathfinder.gov.bc.ca, if left blank a value will be defaulted.
  displayName: Application Domain
- name: CPU_REQUEST
  displayName: CPU Request
  description: Starting amount of CPU the container can use.
  value: 10m
- name: CPU_LIMIT
  displayName: CPU Limit
  description: Maximum amount of CPU the container can use.
  value: 500m
- name: MEMORY_REQUEST
  displayName: Memory Request
  description: Starting amount of memory the container can use.
  value: 10Mi
- name: MEMORY_LIMIT
  displayName: Memory Limit
  description: Maximum amount of memory the container can use.
  value: 512Mi
- name: VECTRONICS_URL
  displayName: VECTRONICS_URL
  description: VECTRONICS_URL
  value: CHANGEME
- name: whis_CHES_API_URL
  displayName: whis_CHES_API_URL
  description: whis_CHES_API_URL
  value: CHANGEME
- name: whis_CHES_AUTH_URL
  displayName: whis_CHES_AUTH_URL
  description: whis_CHES_AUTH_URL
  value: CHANGEME
- name: whis_CHES_TO_EMAIL
  displayName: whis_CHES_TO_EMAIL
  description: whis_CHES_TO_EMAIL
  value: CHANGEME
- name: whis_CHES_FROM_EMAIL
  displayName: whis_CHES_FROM_EMAIL
  description: whis_CHES_FROM_EMAIL
  value: CHANGEME
  



